pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout the GitHub repository
                checkout scm
            }
        }
    }
        stage('Set Git Commit Hash') {
        steps {
            script {
                GIT_COMMIT_HASH = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                echo "Git Commit Hash: ${GIT_COMMIT_HASH}"
            }
        }
    }
}