pipeline {
    agent any

    environment {
        COMPOSE_PROJECT_NAME = 'bank-project'
        DOCKERHUB_CREDENTIALS = credentials('docker-hub-credentials')  // 옵션, 나중에 쓰고 싶으면
        GIT_COMMIT_HASH = ''
    }

    stages {
        stage('Checkout') {
            steps {
                echo "🔄 Git Checkout 시작"   
                checkout scm
            }
        }

        stage('Set Git Commit Hash') {
            steps {
                script {
                    GIT_COMMIT_HASH = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                    echo "Git Commit Hash: ${GIT_COMMIT_HASH}"
                }
            }
        }

        stage('Build Docker Image') {
                steps {
                    // 도커 이미지 빌드
                    sh 'docker build -t your-docker-image-name .'
                }
            }
    }

    post {
        success {
            echo '🏗️ Docker Compose Build & Up 성공!'
        }
        failure {
            echo '❌ Docker Compose 실패'
        }
    }
}